services:
    redaktilo.content_factory:
        class: Gnugat\Redaktilo\Service\ContentFactory
        public: false

    redaktilo.filesystem:
        class: Gnugat\Redaktilo\Service\Filesystem
        public: false
        arguments:
            - "@redaktilo.line_break"
            - "@filesystem"

    redaktilo.line_break:
        class: Gnugat\Redaktilo\Service\LineBreak
        public: false
